In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('framingham_heart_disease.csv')
dataset.head()

   male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0

[5 rows x 16 columns]

In [ ]:
#dataset.isnull().sum()
#dataset.dtypes
        
data = dataset.drop(['education','BPMeds','totChol','BMI','glucose','heartRate' ], axis = 'columns')
data.head()

   male  age  currentSmoker  cigsPerDay  ...  diabetes  sysBP  diaBP  TenYearCHD
0     1   39              0         0.0  ...         0  106.0   70.0           0
1     0   46              0         0.0  ...         0  121.0   81.0           0
2     1   48              1        20.0  ...         0  127.5   80.0           0
3     0   61              1        30.0  ...         0  150.0   95.0           1
4     0   46              1        23.0  ...         0  130.0   84.0           0

[5 rows x 10 columns]

In [ ]:
cigarettes = data['cigsPerDay']
cigarettes.head()
#cig = cigs.mean()
cig = cigarettes.mean()

import math
integer_value = math.floor(cig)
cigarettes.fillna(integer_value, inplace = True)
#hr.fillna(integer_value, inplace = True)
data.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
prevalentStroke    0
prevalentHyp       0
diabetes           0
sysBP              0
diaBP              0
TenYearCHD         0
dtype: int64

In [ ]:
#this data is labeled data
#independent variable (X) will be Age, Estimated Salary
#dependent variable(y) will be Purcahsed (It will be lable)

#define X,y
X = dataset.iloc[:, [ 1, 3]].values
y = dataset.iloc[:, 15].values

#print X,y
# print(X[:5, :])
# print(y[:5])



#import train_test_split from sklearn to train and test our data
from sklearn.model_selection import train_test_split 
#define 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

#print
print(X_train[:5],'\n', '\n', y_train[:5],'\n','\n', X_test[:5],'\n','\n', y_test[:5])

[[42  1]
 [57  0]
 [44  1]
 [58  0]
 [61  1]]

 [0 0 0 1 0]

 [[47  1]
 [55  0]
 [61  1]
 [46  0]
 [39  0]]

 [0 0 0 0 0]

In [ ]:
#dataset.info()
#check corelation among attributes of dataset 
dataset.corr()

                     male       age  education  ...  heartRate   glucose  TenYearCHD
male             1.000000 -0.029014   0.017415  ...  -0.116932  0.005979    0.088374
age             -0.029014  1.000000  -0.166356  ...  -0.012843  0.122356    0.225408
education        0.017415 -0.166356   1.000000  ...  -0.054182 -0.035843   -0.054248
currentSmoker    0.197026 -0.213662   0.018528  ...   0.062686 -0.056726    0.019448
cigsPerDay       0.317143 -0.192959   0.008323  ...   0.075564 -0.058886    0.057755
BPMeds          -0.052504  0.123052  -0.010898  ...   0.015230  0.051197    0.087519
prevalentStroke -0.004550  0.057679  -0.035142  ...  -0.017674  0.018440    0.061823
prevalentHyp     0.005853  0.306799  -0.081726  ...   0.146815  0.086656    0.177458
diabetes         0.015693  0.101314  -0.038749  ...   0.048986  0.617630    0.097344
totChol         -0.070413  0.262554  -0.023613  ...   0.091127  0.046538    0.082369
sysBP           -0.035879  0.394053  -0.129496  ...   0.182155  0.140573    0.216374
diaBP            0.058199  0.205586  -0.061919  ...   0.181021  0.061075    0.145112
BMI              0.081871  0.136096  -0.137747  ...   0.067451  0.087389    0.075300
heartRate       -0.116932 -0.012843  -0.054182  ...   1.000000  0.094546    0.022907
glucose          0.005979  0.122356  -0.035843  ...   0.094546  1.000000    0.125590
TenYearCHD       0.088374  0.225408  -0.054248  ...   0.022907  0.125590    1.000000

[16 rows x 16 columns]

In [ ]:
#normalization and feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

print(X_train[:5], '\n','\n', X_test[:5])

[[-0.88733772  1.00314961]
 [ 0.85318408 -0.99686027]
 [-0.65526815  1.00314961]
 [ 0.96921887 -0.99686027]
 [ 1.31732323  1.00314961]]

 [[-0.30716378  1.00314961]
 [ 0.62111451 -0.99686027]
 [ 1.31732323  1.00314961]
 [-0.42319857 -0.99686027]
 [-1.23544208 -0.99686027]]

In [ ]:
#create object of LogisticRegression class to refer as classifier
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(X_test[:5], '\n', '\n', y_pred[:5])

[[-0.30716378  1.00314961]
 [ 0.62111451 -0.99686027]
 [ 1.31732323  1.00314961]
 [-0.42319857 -0.99686027]
 [-1.23544208 -0.99686027]]

 [0 0 0 0 0]

In [ ]:
print(y_pred[:20],'\n','\n',y_test[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0]

In [ ]:
print(sum(y_pred[:12]),'/',sum(y_test[:12]))

0 / 3

In [ ]:
#we'll use a Confusion Matrix to evaluate exactly how accurate our Logistic Regression model is,
#the more the matching values, more is the accuracy

from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_pred)
matrix

array([[901,   0],
       [159,   0]])